## Transformation of a second rank tensor

In [1]:
import numpy as np

### Kronecker delta $\delta_{ij}$

In [2]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Permutation or Levi-Cevita symbol $\epsilon_{ijk}$

In [3]:
e = np.array([[[0,0,0],[0,0,1],[0,-1,0]],[[0,0,-1],[0,0,0],[1,0,0]],[[0,1,0],[1,0,0],[0,0,0]]])
print(e)

[[[ 0  0  0]
  [ 0  0  1]
  [ 0 -1  0]]

 [[ 0  0 -1]
  [ 0  0  0]
  [ 1  0  0]]

 [[ 0  1  0]
  [ 1  0  0]
  [ 0  0  0]]]


### Consider a $60^{\circ}$ rotation of tensor $T$ about [001] direction

In [4]:
theta = (np.pi)/3
n = np.array([0.0,0.0,1.0])

T = np.array([[1, 0, 3], [0, 2, 2], [3, 2, 4]])

### Transformation of reference frames obtained by rotating about a unit vector n by an angle $\theta$ is written in a compact form as $Q$

In [5]:
Q = np.cos(theta)*d + (n*n.reshape(-1,1))*(1 - np.cos(theta)) + np.einsum('ijk,k->ij',e,n)*np.sin(theta)
print(Q)

[[ 0.5        0.8660254  0.       ]
 [-0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]


### Tensor $T$ in the new reference frame

In [6]:
Tnew = np.einsum('pi,qj,ij->pq', Q, Q, T)
print(Tnew)

[[ 1.75        0.4330127   3.23205081]
 [ 0.4330127   1.25       -1.59807621]
 [ 3.23205081 -1.59807621  4.        ]]
